# Generated by Django 3.0.6 on 2020-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('user_name', models.CharField(default=None, max_length=100)),
                ('token', models.CharField(blank=True, max_length=2000, unique=True)),
                ('phone_number', models.CharField(default=None, max_length=10)),
                ('employee_id', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
