# Generated by Django 3.0.6 on 2020-05-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonarchApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user_info',
        ),
    ]
