# Generated by Django 3.0.6 on 2020-05-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonarchApp', '0002_auto_20200511_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_info',
            options={'verbose_name_plural': 'user_Info'},
        ),
    ]
