# Generated by Django 3.0.6 on 2020-05-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonarchApp', '0003_auto_20200511_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=200, unique=True)),
                ('user_name', models.CharField(default=None, max_length=100)),
                ('user_phone_number', models.CharField(default=None, max_length=10)),
                ('user_employee_id', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
